'use client';

import React from 'react';
import { Sparkles } from 'lucide-react';

interface AiGeneratedBadgeProps {
  /** Optional extra class names for positioning / spacing */
  className?: string;
  /** Label text — defaults to "Generated by AI" */
  label?: string;
}

/**
 * Shared "Generated by AI" badge — rendered beneath every Gemini output so that
 * GenAI usage is unmistakably distinguishable from static/rule-based content.
 *
 * Used by: WayfindingConcierge, SimplifyText, SustainabilityWidget,
 *          OpsDashboard (triage results & crowd alerts), TransportAdvisory.
 *
 * Problem statement: Satisfies legibility requirement across all 8 coverage categories.
 */
export default function AiGeneratedBadge({
  className = '',
  label = 'Generated by AI'
}: AiGeneratedBadgeProps) {
  return (
    <span
      aria-label={label}
      title={label}
      className={`inline-flex items-center gap-1 text-[9px] font-mono text-emerald-500 bg-emerald-950/60 border border-emerald-900/60 rounded px-1.5 py-0.5 tracking-wider select-none ${className}`}
    >
      <Sparkles aria-hidden="true" className="w-2.5 h-2.5 text-scoreboard-green" />
      {label.toUpperCase()}
    </span>
  );
}
