import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import AiGeneratedBadge from './AiGeneratedBadge';

/**
 * Unit tests for the shared AiGeneratedBadge component.
 * Ensures the badge renders correctly with default and custom label text,
 * and carries an accessible aria-label for screen readers.
 */
describe('AiGeneratedBadge', () => {
  it('renders default label text', () => {
    render(<AiGeneratedBadge />);
    // Query by aria-label for precision (avoids matching the wrapping div)
    const badge = screen.getByLabelText('Generated by AI');
    expect(badge).toBeInTheDocument();
    expect(screen.getByText('GENERATED BY AI')).toBeInTheDocument();
  });

  it('renders custom label text when provided', () => {
    render(<AiGeneratedBadge label="Carbon estimate by Gemini AI" />);
    expect(screen.getByText('CARBON ESTIMATE BY GEMINI AI')).toBeInTheDocument();
  });

  it('has aria-label attribute for screen reader accessibility', () => {
    const { container } = render(<AiGeneratedBadge label="Simplified by Gemini AI" />);
    const badge = container.querySelector('[aria-label="Simplified by Gemini AI"]');
    expect(badge).not.toBeNull();
  });

  it('applies extra className when provided', () => {
    const { container } = render(<AiGeneratedBadge className="mt-2" />);
    const badge = container.firstChild as HTMLElement;
    expect(badge.className).toContain('mt-2');
  });
});
